export const PERM_VIEW_ACCOUNT_DETAILS = import.meta.env
    .VITE_PERMISSION_VIEW_ACCOUNT_DETAILS;
export const PERM_EDIT_TAX_INFORMATION = import.meta.env
    .VITE_PERMISSION_EDIT_TAX_INFORMATION;
export const PERM_REMOVE_ACCOUNT = import.meta.env.VITE_PERMISSION_REMOVE_ACCOUNT;
export const PERM_APPOINTMENT = import.meta.env.VITE_PERMISSION_APPOINTMENT;
export const PERM_INITIATE_APPLICATION = import.meta.env
    .VITE_PERMISSION_INITIATE_APPLICATION;
export const PERM_VIEW_ACTIVE_APPLICATIONS = import.meta.env
    .VITE_PERMISSION_VIEW_ACTIVE_APPLICATIONS;
export const PERM_VIEW_APPLICATION_DETAIL = import.meta.env
    .VITE_PERMISSION_VIEW_APPLICATION_DETAIL;
export const PERM_VIEW_RECORD = import.meta.env.VITE_PERMISSION_VIEW_RECORD;
export const PERM_VIEW_PROCESS = import.meta.env.VITE_PERMISSION_VIEW_PROCESS;
export const PERM_VIEW_CASE_FILE = import.meta.env.VITE_PERMISSION_VIEW_CASE_FILE;
export const PERM_APPROVE_CASE_FILE = import.meta.env.VITE_PERMISSION_APPROVE_CASE_FILE;
export const PERM_UPDATE_DOCUMENT_STATUS = import.meta.env
    .VITE_PERMISSION_UPDATE_DOCUMENT_STATUS;
export const PERM_REQUEST_DOCUMENT_FIX = import.meta.env
    .VITE_PERMISSION_REQUEST_DOCUMENT_FIX;
export const PERM_LAWYER_ALERTS = import.meta.env.VITE_PERMISSION_LAWYER_ALERTS;
export const PERM_CLIENT_ALERTS = import.meta.env.VITE_PERMISSION_CLIENT_ALERTS;
export const PERM_ASSIGN_APPLICATIONS = import.meta.env
    .VITE_PERMISSION_ASSIGN_APPLICATIONS;
export const PERM_ARCHIVE_CASE_FILE = import.meta.env.VITE_PERMISSION_ARCHIVE_CASE_FILE;
export const PERM_ACCESS_PROCESS_SETTINGS = import.meta.env
    .VITE_PERMISSION_ACCESS_PROCESS_SETTINGS;
export const PERM_CREATE_PROCESS = import.meta.env.VITE_PERMISSION_CREATE_PROCESS;
export const PERM_EDIT_PROCESS = import.meta.env.VITE_PERMISSION_EDIT_PROCESS;
export const PERM_DELETE_PROCESS = import.meta.env.VITE_PERMISSION_DELETE_PROCESS;
export const PERM_REGISTER_EMPLOYEE = import.meta.env.VITE_PERMISSION_REGISTER_EMPLOYEE;
export const PERM_REMOVE_ACCOUNT_ADMIN = import.meta.env.VITE_PERMISSION_REMOVE_ACCOUNT;
export const PERM_VIEW_USERS = import.meta.env.VITE_PERMISSION_VIEW_USERS;
export const PERM_ADD_ROLE = import.meta.env.VITE_PERMISSION_ADD_ROLE;
export const PERM_UPDATE_ROLE_PERMISSIONS = import.meta.env
    .VITE_PERMISSION_UPDATE_ROLE_PERMISSIONS;
export const PERM_REMOVE_ROLE = import.meta.env.VITE_PERMISSION_REMOVE_ROLE;
export const PERM_AUDIT_HISTORY_ACCESS = import.meta.env
    .VITE_PERMISSION_AUDIT_HISTORY_ACCESS;
export const PERM_UPDATE_ROLE = import.meta.env.VITE_PERMISSION_UPDATE_ROLE;
export const PERM_CREATE_JOB_POSTING = import.meta.env.VITE_PERMISSION_CREATE_JOB_POSTING;
export const PERM_EDIT_JOB_POSTING = import.meta.env.VITE_PERMISSION_EDIT_JOB_POSTING;
export const PERM_DELETE_JOB_POSTING = import.meta.env.VITE_PERMISSION_DELETE_JOB_POSTING;
export const PERM_VIEW_APPLICANT_LIST = import.meta.env
    .VITE_PERMISSION_VIEW_APPLICANT_LIST;
export const PERM_ADD_USER_GUIDE = import.meta.env.VITE_PERMISSION_ADD_USER_GUIDE;
export const PERM_REMOVE_USER_GUIDE = import.meta.env.VITE_PERMISSION_REMOVE_USER_GUIDE;
export const PERM_UPDATE_USER_GUIDE = import.meta.env.VITE_PERMISSION_UPDATE_USER_GUIDE;
export const PERM_VIEW_ASSIGNED_APPLICATIONS = import.meta.env
    .VITE_PERMISSION_VIEW_ASSIGNED_APPLICATIONS;
export const PERM_VIEW_GROUP_APPLICATIONS = import.meta.env
    .VITE_PERMISSION_VIEW_GROUP_APPLICATIONS;